alipay:
  # 支付宝应用 APPID。
  # 示例: 2021000118630011
  appId: ${ALIPAY_APPID:}
  # 商户私钥（PKCS8）。
  # 示例: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBK...
  private-key: ${ALIPAY_PRIVATE_KEY:}
  # 支付宝公钥。
  # 示例: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMI...
  alipay-public-key: ${ALIPAY_ALIPAY_PUBLIC_KEY:}
  # 支付网关地址。
  # 示例: https://openapi.alipay.com/gateway.do
  gatewayUrl: ${ALIPAY_GATEWAY_URL:https://openapi-sandbox.dl.alipaydev.com/gateway.do}
  # Admin 异步通知回调地址。
  # 示例: http://127.0.0.1:8080/order/alipay/notify
  notifyUrl: ${ALIPAY_ADMIN_NOTIFY_URL:http://127.0.0.1:8080/order/alipay/notify}
  # Admin 支付成功页面跳转地址。
  # 示例: http://127.0.0.1:8081/success.html
  returnUrl: ${ALIPAY_ADMIN_RETURN_URL:http://127.0.0.1:8081/success.html}
  # 签名算法。
  # 示例: RSA2
  signType: RSA2
  # 请求字符集。
  # 示例: utf-8
  charset: utf-8
