spring:
  ai:
    openai:
      api-key: ${DASHSCOPE_API_KEY}
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      chat:
        options:
          model: qwen3-max
      embedding:
        options:
          model: text-embedding-v3
          dimensions: 1024
    vectorstore:
      milvus:
        client:
          host: localhost
          port: 19530
        embedding-dimension: 1024
        collection-name: medicine
logging:
  level:
    root: INFO
    org.springframework.ai: DEBUG
    org.springframework.web.client: DEBUG
    org.springframework.web.client.RestClient: TRACE
    org.springframework.http: TRACE
    org.apache.hc.client5.http: DEBUG
