spring:
  ai:
    openai:
      # 这边不要删除，这是占位符,数据库模型信息会从数据库进行读取,如果删除了会导致系统启动失败
      api-key: _
logging:
  level:
    root: INFO
    org.springframework.ai: DEBUG
    org.springframework.web.client: DEBUG
    org.springframework.web.client.RestClient: TRACE
    org.springframework.http: TRACE
    org.apache.hc.client5.http: DEBUG

