spring:
  ai:
    openai:
      api-key: ${DASHSCOPE_API_KEY}
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      chat:
        options:
          model: qwen3-max
      embedding:
        options:
          model: text-embedding-v3
          dimensions: 1024
    vectorstore:
      milvus:
        client:
          host: localhost
          port: 19530
        embedding-dimension: 1024
        collection-name: kb_8
        database-name: medicine
        index-type: IVF_FLAT
        metric-type: COSINE
        initialize-schema: true
#logging:
#  level:
#    org.springframework.ai.chat.client.advisor: DEBUG
